import { type Metadata } from "next";
import { Jost } from "next/font/google";
import "~/app/globals.css";
import { Toaster } from "~/components/ui/sonner";

export const metadata: Metadata = {
  title: "Keyless",
  description: "Generated by create-t3-app",
  icons: {
    icon: "/icon.png",
  },
};

const font = Jost({ subsets: ["latin"] });

const Layout = ({ children }: React.PropsWithChildren) => {
  return (
    <html lang="en">
      <body className={font.className}>
        {children}
        <Toaster theme="light" toastOptions={{ className: font.className }} />
      </body>
    </html>
  );
};

export default Layout;
